all:
	clang -std=c99 -o recvfrom recvfrom.c
	clang -std=c99 -o sendto sendto.c
	clang -std=c99 -o broadcast broadcast.c
	#clang -std=c99 -o multicast1 multicast1.c
	clang -std=c99 -o multicast_send multicast_send.c
	clang -std=c99 -o multicast_recv multicast_recv.c
