version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.20
    steps:
      - checkout
      - run:
          name: Lint
          command: make lint
      - run:
          name: Network routes
          command: cat /proc/net/fib_trie
      - run:
          name: Build
          command: make
      - run:
          name: Run tests
          command: make test
      - run:
          name: Run benchmarks
          command: make bench
