[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mio = { version = "0.8.*", features = ["os-poll", "net"] }
affinity = "0.1.2"
libc = "0.2.153"
